spring:
  neo4j:
    uri: ${NEO4J_URI}
  ai:
    vectorstore:
      neo4j:
        initialize-schema: true
        database-name: neo4j
        index-name: custom-index
        dimensions: 1024
        distance-type: cosine
    ollama:
      base-url: ${OLLAMA_BASE_URL}
      chat:
        model: MFDoom/deepseek-r1-tool-calling:32b
      embedding:
        model: mxbai-embed-large
    mcp:
      client:
        enabled: true
        name: poop-mcp-client
        version: 1.0.0
        request-timeout: 30s
        type: SYNC  # or ASYNC for reactive applications
        toolcallback:
          enabled: true
        sse:
          connections:
            server1:
              url: ${MCP_SERVER}
  application:
    name: poop-mcp-client
server:
  port: 8881
hyperAGI:
  api: ${HYPER_AGI_API}
logging:
  level:
    org:
      springframework:
        ai:
          vectorstore: DEBUG